### PR TITLE
Feature activity

### PR DESCRIPTION
**Pull request by pointlander**

### CODE REVIEW

**Comment by fm-tibco** [comment]
@mellistibco should we consider moving the goja activity to the core contrib or its own repo? Seems like it can be useful to the other actions.

**Comment by mellistibco** [comment]
👍 @fm-tibco. I think the js activity should probably be a standalone repo. Seems like a useful thing someone would want to leverage regardless of the action...

**Comment by mellistibco** [comment]
@pointlander can we pull out the js execute activity and place it into its own repo? What do you think the repo should be named?

**Comment by pointlander** [comment]
@mellistibco The javascript activity can be in a repo named js-activity or javascript-activity.

**Comment by mellistibco** [comment]
@pointlander I created a `jsexec` repo.

**Comment by fm-tibco** [comment]
I think I prefer js-activity as the repo... thoughts?  Btw, @mellistibco did you review the PR?

**Pull request merged**
